- name: "Create backup copy of mirror-list"
  ansible.builtin.copy:
    src: "{{ mirrors_file }}"
    dest: "{{ mirrors_bkup }}"
    force: true
  become: true
  become_user: root

- name: "Find fastest servers, and replace the current mirror-list"
  ansible.builtin.command: reflector {{ repo_update_params }} --save {{ mirrors_file|quote }}
  become: true
  become_user: root

