- name: "Check if mirrorlist exceeds age criteria"
  ansible.builtin.find:
    paths: "{{ pkg_repo_list_file_path | dirname }}"
    patterns: >-
      ^{{ pkg_repo_list_file_path | basename }}$
    use_regex: true
    age: "{{ pkg_repo_list_age_cutoff }}"
  register: mirrors_found
  changed_when: mirrors_found.matched > 0

- name: "Update Arch Linux mirrorlist"
  ansible.builtin.include_tasks: inc/archlinux/do_archlinux_update.yml
  vars:
    mirrors_file: "{{ pkg_repo_list_file_path }}"
    mirrors_bkup: "{{ pkg_repo_list_file_path | dirname }}/{{ pkg_repo_list_bkup_filename }}"
  when: mirrors_found.changed

