- name: "Update 'mirrorlist' file, for Arch Linux"
  ansible.builtin.include_tasks: inc/archlinux/update_repos_arch.yml
  # WARNING: updating mirrors without ensuing sys-upgrade not recommended:
  # See https://wiki.archlinux.org/index.php/Mirrors#Force_pacman_to_refresh_the_package_lists
  vars:
    pkg_repo_list_file_path: "/etc/pacman.d/mirrorlist"
    pkg_repo_list_bkup_filename: "mirrorlist_bkup"
    pkg_repo_list_age_cutoff: "1s"
  when: ansible_os_family == "Archlinux"

