- name: "Configure 'mirrorlist' file updates, for Arch Linux"
  ansible.builtin.include_tasks: archlinux/main.yml
  when: ansible_os_family == "Archlinux"

- name: "Run all notified role-handlers now"
  meta: flush_handlers

