- name: "Create '/usr/local/bin/' utility scripts"
  ansible.builtin.template:
    dest: "/usr/local/bin/{{ script_name }}.sh"
    src: "{{ script_name }}.j2"
    owner: 'root'
    group: 'root'
    mode: '755'
    force: yes
  become: true
  become_user: root
  loop:
    - 'do_mirrors_sysupgrade'
    - 'do_package_cleanup'
    - 'do_pacnew_merge'
  loop_control:
    loop_var: script_name

- name: "Install 'reflector' package, for mirrorlist update support"
  community.general.pacman:
    name: reflector
    state: present
  become: true
  become_user: root

- name: "Install 'pacman-contrib' package, for paccache utility"
  community.general.pacman:
    name: pacman-contrib
    state: present
  become: true
  become_user: root

- name: "Check if basic terminal 'vim' package is installed"
  ansible.builtin.command: pacman -Qi vim
  register: vim_result
  changed_when: false
  failed_when: vim_result.rc > 1

- name: "Check if GUI 'gvim' package (with clipboard support) is installed"
  ansible.builtin.command: pacman -Qi gvim
  register: gvim_result
  changed_when: gvim_result.rc == 1
  failed_when: gvim_result.rc > 1
  notify: install-term-vim
  when: vim_result.rc == 1

