- name: "Create '/usr/local/bin/' utility scripts"
  ansible.builtin.template:
    dest: "/usr/local/bin/{{ script_name }}.sh"
    src: "freebsd/{{ script_name }}.j2"
    owner: 'root'
    group: 'wheel'
    mode: '755'
    force: yes
  become: true
  become_user: root
  loop:
    - 'do_upgrade'
  loop_control:
    loop_var: script_name

- name: "Create alias 'pkg details' in {{ pkg_conf_file_path }}"
  ansible.builtin.lineinfile:
    path: "{{ pkg_conf_file_path }}"
    insertafter: >-
      ^ALIAS(.*)\{$
    line: '  details = search -Q name -Q version -Q www -Q licenses -Q maintainer -Q depends-on -Q required-by,'
    state: present
  become: true
  become_user: root

