- name: "Create pkg cmd alias for {{ alias_descrip }}"
  ansible.builtin.include_tasks: add_pkg_alias.yml
  vars:
    alias_name: "{{ pkg_alias_remote_repo_search }}"
    alias_command: ' = search'
    alias_descrip: 'remote-repo pkg search'

- name: "Create pkg cmd alias for {{ alias_descrip }}"
  ansible.builtin.include_tasks: add_pkg_alias.yml
  vars:
    alias_name: "{{ pkg_alias_remote_repo_details }}"
    alias_command: ' = search -Q name -Q comment -Q version -Q www -Q licenses -Q maintainer -Q depends-on -Q required-by'
    alias_descrip: 'remote-repo pkg details'

