- name: "Create '/usr/local/bin/' utility scripts"
  ansible.builtin.template:
    dest: "/usr/local/bin/{{ script_name }}.sh"
    src: "{{ script_name }}.j2"
    owner: 'root'
    group: 'root'
    mode: '755'
    force: yes
  become: true
  become_user: root
  loop:
    - 'archlinux/do_mirrors_sysupgrade'
    - 'archlinux/do_package_cleanup'
    - 'archlinux/do_pacnew_merge'
  loop_control:
    loop_var: script_name

